name: PyTest

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: PyTest (${{ matrix.os }}, ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: interscript/maps
        path: maps
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: pip install -e ".[dev]"
    - run: pytest tests/ -v
      env:
        INTERSCRIPT_MAPS_PATH: ${{ github.workspace }}/maps/maps
